---

- hosts: all

  tasks:

  - name: Install distribution packages
    apt:
      name:
      - build-essential
      - libxml2-dev
      - libxslt-dev
      - zlib1g-dev
      - python3-dev
      - python3-pip
      - python3-venv
      - python3-psycopg2
      - git
      - nginx
      - postgresql
      - pandoc
      - texlive
      - texlive-xetex
      - lmodern
      - librsvg2-bin
      state: latest

  - name: Create rdmo user
    user:
      name: "{{ rdmo_user }}"
      home: "{{ rdmo_home }}"
      comment: "RDMO user"
      shell: /bin/bash
      create_home: yes
      state: present

  # nginx

  - name: Obtain certificate for {{ rdmo_host }}
    command:
      cmd: |
        certbot certonly --standalone --nginx -d {{ rdmo_host }}
        --non-interactive --agree-tos --email {{ certbot_email }}
      creates: /etc/letsencrypt/live/{{ rdmo_host }}/cert.pem

  - name: Deploy nginx config file
    template:
      src: templates/rdmo.conf
      dest: "/etc/nginx/sites-available/{{ rdmo_host }}.conf"

  - name: Enable nginx config file
    file:
      src: /etc/nginx/sites-available/{{ rdmo_host }}.conf
      dest: /etc/nginx/sites-enabled/{{ rdmo_host }}.conf
      state: link
    notify: Restart nginx

  # systemd

  - name: Deploy systemd service file
    template:
      src: templates/rdmo.service
      dest: "/etc/systemd/system/{{ rdmo_service }}.service"

  - name: Create log directory
    file:
      path: "/var/log/django/{{ rdmo_service }}"
      state: directory
      owner: "{{ rdmo_user }}"
      group: "{{ rdmo_user }}"
      mode: '0755'

  # postgres

  - name: Create rdmo postgres user
    become: true
    become_user: postgres
    postgresql_user:
      name: "{{ rdmo_user }}"
      role_attr_flags: CREATEDB,NOSUPERUSER

  - name: Create rdmo postgres database
    become: true
    become_user: postgres
    postgresql_db:
      name: "{{ rdmo_dbname }}"
      owner: "{{ rdmo_user }}"

  # rdmo-app

  - name: Clone rdmo-app repository
    become: yes
    become_user: "{{ rdmo_user }}"
    git:
      repo: "{{ rdmo_app_repo }}"
      dest: "{{ rdmo_app_path }}"
      version: main
      accept_hostkey: yes

  - name: Create virtual environment
    become: yes
    become_user: "{{ rdmo_user }}"
    command:
      cmd: "python3 -m venv {{ rdmo_venv }}"
      creates: "{{ rdmo_venv }}/bin/activate"

  - name: Upgrade pip inside virtualenv
    become: yes
    become_user: "{{ rdmo_user }}"
    pip:
      name: pip
      state: latest
      virtualenv: "{{ rdmo_venv }}"
      virtualenv_command: "python3 -m venv"

  - name: Install rdmo inside virtualenv
    become: yes
    become_user: "{{ rdmo_user }}"
    pip:
      name: "{{ rdmo_dist }}"
      state: latest
      virtualenv: "{{ rdmo_venv }}"
      virtualenv_command: "python3 -m venv"

  - name: Deploy local.py config file
    become: yes
    become_user: "{{ rdmo_user }}"
    template:
      src: templates/local.py
      dest: "{{ rdmo_app_path }}/config/settings/local.py"

  # rdmo

  - name: Init RDMO
    become: yes
    become_user: "{{ rdmo_user }}"
    command:
      cmd: "{{ rdmo_venv }}/bin/python {{ rdmo_app_path }}/manage.py upgrade"
      creates: "{{ rdmo_app_path }}/static_root"
    notify: Restart rdmo

  handlers:

  - name: Restart nginx
    systemd:
      name: nginx
      state: restarted

  - name: Restart rdmo
    systemd:
      name: "{{ rdmo_service }}"
      enabled: true
      daemon_reload: true
      state: restarted
