---

- hosts: all

  tasks:

  - name: Configure RDMO sites from legacy variables
    set_fact:
      rdmo_sites_effective:
      - host: "{{ rdmo_host }}"
        service: "{{ rdmo_service }}"
        app_repo: "{{ rdmo_app_repo }}"
        app_path: "{{ rdmo_app_path }}"
        dist: "{{ rdmo_dist }}"
        user: "{{ rdmo_user }}"
        home: "{{ rdmo_home }}"
        venv: "{{ rdmo_venv }}"
        dbname: "{{ rdmo_dbname }}"
        django_secret_key: "{{ django_secret_key }}"
    when: rdmo_sites is not defined

  - name: Configure RDMO sites
    set_fact:
      rdmo_sites_effective: "{{ rdmo_sites }}"
    when: rdmo_sites is defined

  - name: Configure unique RDMO virtual environments
    set_fact:
      rdmo_virtualenvs_effective: []

  - name: Add unique RDMO virtual environments
    set_fact:
      rdmo_virtualenvs_effective: "{{ rdmo_virtualenvs_effective + [{'venv': item.venv | default(rdmo_venv), 'user': item.user | default(rdmo_user), 'dist': item.dist | default(rdmo_dist)}] }}"
    when: (item.venv | default(rdmo_venv)) not in (rdmo_virtualenvs_effective | map(attribute='venv') | list)
    loop: "{{ rdmo_sites_effective }}"
    loop_control:
      label: "{{ item.venv | default(rdmo_venv) }}"

  - name: Install distribution packages
    apt:
      name:
      - build-essential
      - libxml2-dev
      - libxslt-dev
      - zlib1g-dev
      - python3-dev
      - python3-pip
      - python3-venv
      - python3-psycopg2
      - git
      - nginx
      - postgresql
      - pandoc
      - texlive
      - texlive-xetex
      - lmodern
      - librsvg2-bin
      state: latest

  - name: Create rdmo users
    user:
      name: "{{ item.user | default(rdmo_user) }}"
      home: "{{ item.home | default(rdmo_home) }}"
      comment: "RDMO user"
      shell: /bin/bash
      create_home: yes
      state: present
    loop: "{{ rdmo_sites_effective }}"
    loop_control:
      label: "{{ item.user | default(rdmo_user) }}"

  # nginx

  - name: Obtain certificates for RDMO sites
    command:
      cmd: |
        certbot certonly --standalone --nginx -d {{ item.host }}
        --non-interactive --agree-tos --email {{ certbot_email }}
      creates: /etc/letsencrypt/live/{{ item.host }}/cert.pem
    loop: "{{ rdmo_sites_effective }}"
    loop_control:
      label: "{{ item.host }}"

  - name: Deploy nginx config files
    template:
      src: templates/rdmo.conf
      dest: "/etc/nginx/sites-available/{{ rdmo_site.host }}.conf"
    loop: "{{ rdmo_sites_effective }}"
    loop_control:
      label: "{{ rdmo_site.host }}"
      loop_var: rdmo_site
    notify: Restart nginx

  - name: Enable nginx config files
    file:
      src: /etc/nginx/sites-available/{{ item.host }}.conf
      dest: /etc/nginx/sites-enabled/{{ item.host }}.conf
      state: link
    loop: "{{ rdmo_sites_effective }}"
    loop_control:
      label: "{{ item.host }}"
    notify: Restart nginx

  # systemd

  - name: Deploy systemd service files
    template:
      src: templates/rdmo.service
      dest: "/etc/systemd/system/{{ rdmo_site.service }}.service"
    loop: "{{ rdmo_sites_effective }}"
    loop_control:
      label: "{{ rdmo_site.service }}"
      loop_var: rdmo_site
    notify: Restart rdmo

  - name: Create log directories
    file:
      path: "/var/log/django/{{ item.service }}"
      state: directory
      owner: "{{ item.user | default(rdmo_user) }}"
      group: "{{ item.user | default(rdmo_user) }}"
      mode: '0755'
    loop: "{{ rdmo_sites_effective }}"
    loop_control:
      label: "{{ item.service }}"

  # postgres

  - name: Create rdmo postgres users
    become: true
    become_user: postgres
    postgresql_user:
      name: "{{ item.user | default(rdmo_user) }}"
      role_attr_flags: CREATEDB,NOSUPERUSER
    loop: "{{ rdmo_sites_effective }}"
    loop_control:
      label: "{{ item.user | default(rdmo_user) }}"

  - name: Create rdmo postgres databases
    become: true
    become_user: postgres
    postgresql_db:
      name: "{{ item.dbname | default(rdmo_dbname) }}"
      owner: "{{ item.user | default(rdmo_user) }}"
    loop: "{{ rdmo_sites_effective }}"
    loop_control:
      label: "{{ item.dbname | default(rdmo_dbname) }}"

  # rdmo-app

  - name: Clone rdmo-app repositories
    become: yes
    become_user: "{{ item.user | default(rdmo_user) }}"
    git:
      repo: "{{ item.app_repo | default(rdmo_app_repo) }}"
      dest: "{{ item.app_path }}"
      version: main
      accept_hostkey: yes
    loop: "{{ rdmo_sites_effective }}"
    loop_control:
      label: "{{ item.app_path }}"

  - name: Create virtual environments
    become: yes
    become_user: "{{ item.user }}"
    command:
      cmd: "python3 -m venv {{ item.venv }}"
      creates: "{{ item.venv }}/bin/activate"
    loop: "{{ rdmo_virtualenvs_effective }}"
    loop_control:
      label: "{{ item.venv }}"

  - name: Upgrade pip inside virtualenvs
    become: yes
    become_user: "{{ item.user }}"
    pip:
      name: pip
      state: latest
      virtualenv: "{{ item.venv }}"
      virtualenv_command: "python3 -m venv"
    loop: "{{ rdmo_virtualenvs_effective }}"
    loop_control:
      label: "{{ item.venv }}"

  - name: Install rdmo inside virtualenvs
    become: yes
    become_user: "{{ item.user }}"
    pip:
      name: "{{ item.dist }}"
      state: latest
      virtualenv: "{{ item.venv }}"
      virtualenv_command: "python3 -m venv"
    loop: "{{ rdmo_virtualenvs_effective }}"
    loop_control:
      label: "{{ item.venv }}"

  - name: Deploy local.py config files
    become: yes
    become_user: "{{ rdmo_site.user | default(rdmo_user) }}"
    template:
      src: templates/local.py
      dest: "{{ rdmo_site.app_path }}/config/settings/local.py"
    loop: "{{ rdmo_sites_effective }}"
    loop_control:
      label: "{{ rdmo_site.host }}"
      loop_var: rdmo_site

  # rdmo

  - name: Init RDMO sites
    become: yes
    become_user: "{{ item.user | default(rdmo_user) }}"
    command:
      cmd: "{{ item.venv | default(rdmo_venv) }}/bin/python {{ item.app_path }}/manage.py upgrade"
      creates: "{{ item.app_path }}/static_root"
    loop: "{{ rdmo_sites_effective }}"
    loop_control:
      label: "{{ item.host }}"
    notify: Restart rdmo

  handlers:

  - name: Restart nginx
    systemd:
      name: nginx
      state: restarted

  - name: Restart rdmo
    systemd:
      name: "{{ item.service }}"
      enabled: true
      daemon_reload: true
      state: restarted
    loop: "{{ rdmo_sites_effective }}"
    loop_control:
      label: "{{ item.service }}"
