server {
    server_name {{ rdmo_site.host }};

    root /var/www/{{ rdmo_site.host }};
    index index.html;

    location /static/ {
        alias {{ rdmo_site.app_path }}/static_root/;
    }

    location / {
        proxy_pass http://unix:/run/gunicorn/{{ rdmo_site.service }}/rdmo.sock;

        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

    listen [::]:443 ssl;
    listen 443 ssl;

    ssl_certificate /etc/letsencrypt/live/{{ rdmo_site.host }}/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/{{ rdmo_site.host }}/privkey.pem;
    ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem;

    include /etc/letsencrypt/options-ssl-nginx.conf;
}

server {
    listen 80;
    listen [::]:80;

    server_name {{ rdmo_site.host }};
    root /var/www/{{ rdmo_site.host }};

    location /.well-known/acme-challenge/ {
        root /var/www/{{ rdmo_site.host }};
    }

    location / {
        return 301 https://$host$request_uri;
    }
}
